# Generated by Django 2.1.2 on 2018-11-15 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('time_taken', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageCoordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('w', models.IntegerField()),
                ('h', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LotState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField()),
                ('lot_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='mainModels.LotState')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_index', models.IntegerField()),
                ('y_index', models.IntegerField()),
                ('lot_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='mainModels.LotState')),
            ],
        ),
        migrations.CreateModel(
            name='SectorSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_coordinates', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sector_spot', to='mainModels.ImageCoordinates')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_spots', to='mainModels.Sector')),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('full', models.BooleanField()),
                ('row', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spots', to='mainModels.Row')),
            ],
        ),
        migrations.CreateModel(
            name='ArduinoOutput',
            fields=[
                ('output_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainModels.Output')),
                ('ip_address', models.IntegerField()),
            ],
            bases=('mainModels.output',),
        ),
        migrations.CreateModel(
            name='CameraHubInput',
            fields=[
                ('input_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainModels.Input')),
                ('ip_address', models.IntegerField()),
                ('hubId', models.IntegerField()),
            ],
            bases=('mainModels.input',),
        ),
        migrations.AddField(
            model_name='sectorspot',
            name='spot',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sector_spot', to='mainModels.Spot'),
        ),
        migrations.AddField(
            model_name='output',
            name='parking_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='mainModels.ParkingLot'),
        ),
        migrations.AddField(
            model_name='lotstate',
            name='parking_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotState', to='mainModels.ParkingLot'),
        ),
        migrations.AddField(
            model_name='input',
            name='parking_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='mainModels.ParkingLot'),
        ),
        migrations.AddField(
            model_name='image',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='mainModels.Sector'),
        ),
        migrations.AddField(
            model_name='camera',
            name='camera_hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='mainModels.CameraHubInput'),
        ),
    ]
