# Generated by Django 2.1.2 on 2018-11-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainModels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arduinooutput',
            name='ip_address',
            field=models.TextField(),
        ),
    ]
