# Generated by Django 2.1.2 on 2018-11-16 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainModels', '0003_auto_20181116_0713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lotstate',
            old_name='activated',
            new_name='active',
        ),
    ]
