# Generated by Django 2.1.2 on 2018-11-16 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainModels', '0004_auto_20181116_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotstate',
            name='parking_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_state', to='mainModels.ParkingLot'),
        ),
    ]
