# Generated by Django 2.1.2 on 2018-11-19 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainModels', '0005_auto_20181116_0716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagecoordinates',
            old_name='h',
            new_name='bottom',
        ),
        migrations.RenameField(
            model_name='imagecoordinates',
            old_name='w',
            new_name='left',
        ),
        migrations.RenameField(
            model_name='imagecoordinates',
            old_name='x',
            new_name='right',
        ),
        migrations.RenameField(
            model_name='imagecoordinates',
            old_name='y',
            new_name='top',
        ),
    ]
