# Generated by Django 2.1.3 on 2018-11-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainModels', '0008_auto_20181126_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='cameraID',
            field=models.CharField(default='1.1', max_length=30),
        ),
    ]
